export const IMAGES = {
  GIVE_UP: "/giveup.png",
  BUTTON: "/button.png",
  ARMOR: "/armor.png",
  GEM: "/gem.png",
  SHOP: "/shop.png",
  BUTTON_YELLOW: "/button-yellow.png",
  TICKET: "/ticket.png",
  SHOP_GEM_1: "/shopgem1.png",
  SHOP_GEM_2: "/shopgem2.png",
  SHOP_GEM_3: "/shopgem3.png",
  BACK_ARROW: "/back-arrow.svg",
  GAME_BG: "https://s3dux5rwcu.ufs.sh/f/3pYCTPyYdTmWkCroS4xNpESWBGz9gjT1xRYHtIreZaJA3Mu7",
  ROADMAP_BG: "https://s3dux5rwcu.ufs.sh/f/3pYCTPyYdTmWFBZpvWdRoqXtcNr8msQ4ObBjiV3e20n5JySx",
  GIFT_BG: "https://s3dux5rwcu.ufs.sh/f/3pYCTPyYdTmWkh2ikpxNpESWBGz9gjT1xRYHtIreZaJA3Mu7",
  FRIENDS_BG: "https://s3dux5rwcu.ufs.sh/f/3pYCTPyYdTmWBcfixi5VL20zUdwJ5Dkotb73Sa8ElYjuCxB4",
  QUESTS_BG: "https://s3dux5rwcu.ufs.sh/f/3pYCTPyYdTmWUCM2kH9thzndp9rDx7cfkvlgICFVWXuHR3qb",
  LOGO: "https://s3dux5rwcu.ufs.sh/f/3pYCTPyYdTmWDiDMJ0QRj5Y3Tn17qWlMCd6irautIgfHA0PL",
};
