import type { Metadata } from "next";
import "./globals.css";
import Script from "next/script";

import { Lilita_One } from 'next/font/google'
import AnalyticsProvider from "@/components/AnalyticsProvider";

const lilita = Lilita_One({
  subsets: ['latin'],
  weight: "400"
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${lilita.className} antialiased`}>
        <AnalyticsProvider>
          {children}
        </AnalyticsProvider>
        <Script
          src="https://telegram.org/js/telegram-web-app.js"
          strategy="beforeInteractive" />
      </body>
    </html>
  );
}
